# permissions for end users to edit objstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objstore-editor-role
rules:
- apiGroups:
  - cninf-oss.oss.fjj.com
  resources:
  - objstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cninf-oss.oss.fjj.com
  resources:
  - objstores/status
  verbs:
  - get
