---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cninf-oss.oss.fjj.com
  resources:
  - objstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cninf-oss.oss.fjj.com
  resources:
  - objstores/finalizers
  verbs:
  - update
- apiGroups:
  - cninf-oss.oss.fjj.com
  resources:
  - objstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
